# Generated by Django 2.0 on 2018-09-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_planterm_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planterm',
            unique_together={('plan', 'payment_term')},
        ),
    ]
